version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./prisma:/app/prisma
    environment:
      - PORT=5000
      - JWT_SECRET=super_secret_key_2035_lifeos
      - DATABASE_URL=file:./dev.db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
